### ISSUE TITLE
trouble getting 'hello world' to work!

### ISSUE THREAD

**Issue by lakamsani** [roylines/node-credstash#35]
Hi, trying to get a small test app working on an EC2 instance with an IAM role (confirmed via curl http://169.254.169.254/latest/meta-data/iam/security-credentials/role-name

Lets call this try.js
````javascript
const Credstash = require('credstash/index.js');
var credstash = new Credstash();

credstash.get('apidev.mongo.pass', (e, secret) => {
    if (e) {
      console.error('error getting secret', e);
    }
    console.log('do not share the secret', secret);
});
````
In package.json, I have:  "credstash" : "1.0.1". 
````bash
% pwd
/home/ec2-user/onkore-node
% npm install
% export AWS_DEFAULT_REGION=us-west-2
% node try.js
````
gives this error:

````bash
error getting secret { ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/event_listeners.js:81:45)
    at Request.callListeners (/home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/config.js:293:7)
    at /home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/config.js:333:9
    at resolveNext (/home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:84:9)
    at /home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:97:11
    at /home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/credentials.js:123:23
    at /home/ec2-user/onkore-node/node_modules/credstash/node_modules/aws-sdk/lib/credentials/ec2_metadata_credentials.js:66:7
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2017-02-09T10:00:58.222Z }
do not share the secret null
````
Tried setting regions like this as well ~/.aws/config
````javascript
[default]
output = json
region = us-west-2
````

I must be missing something obvious here. Thoughts? thx.

**Comment by lakamsani** [comment]
Found https://github.com/DavidTanner/nodecredstash and that is  working for me. Will use that for now.

**Comment by tomgoren** [comment]
@lakamsani see @roylines' note in https://github.com/roylines/node-credstash#installation:
> Ensure you have AWS credentials configured.

You might want to check out [Amazon's instructions for setting up the default region for the JS SDK](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html).

**Comment by coltonone20** [comment]
Yes this library requires that AWS_DEFAULT_REGION be set

`AWS_DEFAULT_REGION=us-west-2 node try.js`
